name: dellight
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  flutter_secure_storage: ^9.2.2

  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.7
  uuid: ^4.5.1
  flutter_lints: ^5.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  connectivity_plus: ^6.1.0
  flutter_native_splash: ^2.4.3
  lottie: ^3.1.3
  permission_handler: ^11.3.1
  flutter_sound: ^9.6.0
  app_settings: ^5.1.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  audio_session: ^0.1.21
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
   ios: true
   android: true
   web: false
   color: "#6B9BFB"
   color_dark: "#381F59"
   image_dark: assets/icon/icon_logo.png
   image: assets/icon/icon_logo.png
   android_12:
      icon_background_color: "#6B9BFB"
      icon_background_color_dark: "#381F59"
      image_dark: assets/icon/icon_logo.png
      image: assets/icon/icon_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/

    - assets/images/icon_logo.png
